# Generated by Django 4.1.5 on 2023-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("details", models.TextField()),
                ("image", models.ImageField(upload_to="slider")),
                ("url", models.TextField(default="#")),
            ],
        ),
    ]
