# Generated by Django 4.1.5 on 2023-01-10 14:51

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_slider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=sorl.thumbnail.fields.ImageField(upload_to="slider"),
        ),
    ]
