# Generated by Django 4.1.5 on 2023-01-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_slider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="slider"),
        ),
    ]
