# Generated by Django 4.1.5 on 2023-01-10 15:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_slider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[1920, 1080],
                upload_to="slider",
            ),
        ),
    ]
