# Generated by Django 4.1.5 on 2023-01-11 13:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_aboutus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("features", models.TextField()),
                (
                    "logo",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        quality=75,
                        scale=0.5,
                        size=[100, 100],
                        upload_to="logo",
                    ),
                ),
            ],
        ),
    ]
