# Generated by Django 4.1.5 on 2023-01-13 06:47

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.TextField()),
                (
                    "logo",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        quality=75,
                        scale=0.5,
                        size=[1197, 777],
                        upload_to="client",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("qualification", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
