# Generated by Django 4.1.5 on 2023-01-13 06:50

from django.db import migrations
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_client_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=django.utils.timezone.now,
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[1197, 777],
                upload_to="team",
            ),
            preserve_default=False,
        ),
    ]
