# Generated by Django 4.1.5 on 2023-01-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloguser",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile/default.jpg",
                null=True,
                upload_to="profile",
            ),
        ),
    ]
