# Generated by Django 4.1.5 on 2023-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0015_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
