# Generated by Django 4.1.5 on 2023-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0017_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="mobile",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
